### ISSUE TITLE
Not able to do light in air touches

### ISSUE THREAD

**Issue by abhishekranaji** [adafruit/Adafruit_CircuitPython_MPR121#29]
I didn't able to figure out how to do in air touches. Mean not actually touching the pad of sensor
And how to detect slide like things
Sorry for the noob like questions , But i am new with this type of things to work in python. I have managed to do these things in Arduino but want to switch these things to python. 
Please help me.
Thank you

**Comment by ladyada** [comment]
you cannot do 'air' touches. this isn't a distance sensor its a touch sensor. for other questions, please post in the forums and someone may reply
